services:
  - type: web
    name: idea-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: idea-postgres
          property: connectionString
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: ZHIPU_API_KEY
        sync: false
      - key: XF_API_KEY
        sync: false
      - key: XF_API_SECRET
        sync: false
      - key: QQ_EMAIL_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /api/health
    
databases:
  - name: idea-postgres
    databaseName: idea_db
    user: idea_user
    plan: free
